### ISSUE TITLE
Support "Do not disturb, priority mode"

### ISSUE THREAD

**Issue by fishnux** [adrcotfas/Goodtime#102]
Hi,

At the moment Goodtime supports the "Do not disturb" mode when starting a new session. I'm requesting a tickbox to use "Priority mode" instead, which is basically "Do not disturb" but allows important contacts to be able to call you during a Goodtime session.

**Comment by adrcotfas** [comment]
Hi,
Isn't this set in the device settings?

**Comment by fishnux** [comment]
Hi,

Important contacts are only able to actually ring the phone if "priority 
mode" is enabled. The standard "do not disturb" mode doesn't allow this, it 
completely silences the phone, even calls from important contacts. Since 
Goodtime is able to turn on "do not disturb" when a session starts it would 
be pretty easy to do the same for "priority mode".

**Comment by adrcotfas** [comment]
I think this is valid only for Lolipop devices or am I wrong? I using some Samsung devices with Kitkat and Oreo to test the app and the apps and contacts allowed to interrupt are set in the settings of the phone if I'm not mistaken (but not on Kitkat, of course).

At the moment, the DND mode is achieved with:
`aManager.setRingerMode(RINGER_MODE_SILENT);`
If you know of other ways to achieve "Priority mode", please leave a comment.

**Comment by adrcotfas** [comment]
This might help:
https://stackoverflow.com/questions/31862753/android-how-to-turn-on-do-not-disturb-dnd-programmatically
I'm trying to implement Priority Mode instead of in the next release.

**Comment by Samyak039** [comment]
> Aren't these exceptions set in the device settings?

how..?

**Comment by dawids21** [comment]
Is there any progress with this? I would really love this feature.

**Comment by adrcotfas** [comment]
This will come in 2.1.18.
