### ISSUE TITLE
implement option to disable data besides WiFi

### ISSUE THREAD

**Issue by adrcotfas** [adrcotfas/Goodtime#12]

**Comment by vlad-i** [comment]
Does this mean to disable only network data?

**Comment by adrcotfas** [comment]
It means disabling data and WiFi during work. At the moment you can only toggle the WiFi.

**Comment by vlad-i** [comment]
as a separate option? or just merge both disabling options in just 1 "disable ALL the data!"

**Comment by adrcotfas** [comment]
I would prefer merging both. I think it makes sense like that.

**Comment by adrcotfas** [comment]
This is not possible with un-rooted devices runing Android L or later.
