### ISSUE TITLE
translate the app and it's Google Play description

### ISSUE THREAD

**Issue by adrcotfas** [adrcotfas/Goodtime#13]

**Comment by adrcotfas** [comment]
Might give https://poeditor.com/ a try.

**Comment by fdw** [comment]
I added the code to translate the app (see #34 ), and a German translation. Other languages can be added separately, for example through poeditor.

Translating the description in the app store can't be done with in the code. I'm not sure how we could/should do this.

**Comment by adrcotfas** [comment]
A POEditor project was created:
https://poeditor.com/projects/view?id=75697
