### ISSUE TITLE
Long break is triggered after second work session

### ISSUE THREAD

**Issue by axelfriberg** [adrcotfas/Goodtime#142]
I've activated long breaks in the app and set the number of session before a long break to 4. The problem is that after just two sessions a long break is activated instead of a short one. I'm using 2.0.10 of the app on Android version 9.

**Comment by adrcotfas** [comment]
Can you please retest by swiping in one direction to cycle though work and break sessions?
The way it's implemented is that a work session will count for the long break whenever a user finishes or skipps it.

**Comment by axelfriberg** [comment]
Unfortunately, it seems like the problem still persists.

**Comment by woj-tek** [comment]
I'm having the same problem. Happens usually when I use swiping to skip current work session.
Just now I have "2" as session count and after swiping it went to long break.

Version 2.0.11

**Comment by adrcotfas** [comment]
@woj-tek Sounds like the expected behavior. A skipped session will not be counted in the statistics (and implicitly in the bottom counter which shows today's finished sessions). But swiping to skip through the work-break-work...-long-break cycle will work independently.

**Comment by woj-tek** [comment]
@adrcotfas why it's expected behaviour? If we don't count those sessions towards finished sessions why they are considered in work-break-long_break cycle? This seems quite inconsistent and counter-intuitive.

Would there be at least possibility to make it optional?

**Comment by adrcotfas** [comment]
@woj-tek
It's for ease of access to long breaks if one desires to start one.
It doesn't break the usual flow if you follow it without skipping and stopping breaks.

I don't plan to create an option for this to not bloat the settings.
