### ISSUE TITLE
Pause dialog disappears when rotating screen

### ISSUE THREAD

**Issue by adriangrupp** [adrcotfas/Goodtime#145]
When I turn the phone after getting the dialog for a completed session the dialog disappears. This way one cannot directly start the break if the screen was rotated beforehand.

**Comment by adrcotfas** [comment]
Sorry for the late reply.
You could use the buttons from the notification which will not disappear.

**Comment by adrcotfas** [comment]
This was fixed and the start break dialog will not disappear anymore.
