### ISSUE TITLE
Play sound one minute before a Pomodoro will end

### ISSUE THREAD

**Issue by sojusnik** [adrcotfas/Goodtime#150]
An optional and configurable sound hint one minute before a Pomodoro is going to expire would allow staying in the flow, because you could easily add some minutes to it before the Pomodoro expires.

**Comment by r4taw2mg** [comment]
I think this should be configurabel as a part of the profile. Si, if you are in a 50/10 mode, the reminder may be set to 5 minutes before the end of the pomodoro.

The reminder should also have an own, configurable sound.

**Comment by adrcotfas** [comment]
This was implemented in v2.2.0. available soon on F-Droid and Google Play.
