### ISSUE TITLE
Make app more discoverable, by adding "pomodoro" somewhere in F-Droid description

### ISSUE THREAD

**Issue by bradyt** [adrcotfas/Goodtime#152]
No apps show up in F-Droid if one searches for "pomodoro". I only found your app when I searched instead for "timer". Perhaps the word "pomodoro" can be added to description so that F-Droid search reveals your app.

**Comment by adrcotfas** [comment]
Sorry for the delay but here's a MR for it:
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6352

**Comment by iootaa** [comment]
That's the way I discovered Good time, thank you!
