### ISSUE TITLE
Suggestion: make break timer colour different from normal timer

### ISSUE THREAD

**Issue by axelsimon** [adrcotfas/Goodtime#156]
Hi,
First of all, thanks for making this app. It's really helpful and pleasant to use. Way to go.

One small issue, when i'm in the last 5 minutes of a work session, i can't tell just from looking at the screen if i'm still in the work session or already in the break. I have to tap the screen and check the icon in the bottom right (timer or cup).

I realised just now, looking at the issues, that it's possible to choose a colour of a work session's timer, by picking a colour for the different profiles (cf #124).
Unfortunately, this doesn't help here, as the timer for breaks is still the same colour as the one for work sessions.

Suggestion: automatically make break timers use a colour that is 50% of the saturation of the work session colour.
Or just make them all light grey.

Thanks!

**Comment by adrcotfas** [comment]
This will come in the next release.

**Comment by adrcotfas** [comment]
Version 2.1.5 contains this improvement.
