### ISSUE TITLE
Hackathon Proposal: FOSS Gamification

### ISSUE THREAD

**Issue by DonaldTsang** [adrcotfas/Goodtime#170]
Things that could be done:
- Dissect the elements of these app
  - https://play.google.com/store/apps/details?id=com.dotsaft.sat.pomodoromoon
  - https://play.google.com/store/apps/details?id=com.wlxd.pomochallenge
- Design the application layout (UI) to be compatible with Goodtime
- Writing the app to be compatible with Goodtime's default workflow

**Comment by adrcotfas** [comment]
Thank you for your interest but I don't think that this is the right place to organize a Hackathon.

**Comment by DonaldTsang** [comment]
@adrcotfas any recommendations if we have no social media?

**Comment by adrcotfas** [comment]
By "we" do you mean you/potential people interested in the hackaton or Goodtime?

**Comment by DonaldTsang** [comment]
Yeah.

**Comment by adrcotfas** [comment]
What about https://www.reddit.com/r/androiddev/?

**Comment by DonaldTsang** [comment]
I am also looking at https://www.reddit.com/search?q=productivity&type=sr for a boost in morale, since it is on-topic for the use of the software.
