### ISSUE TITLE
Setting "Disable Wi-fi" does not work.

### ISSUE THREAD

**Issue by BorisB** [adrcotfas/Goodtime#172]
Steps to reproduce:
- I enable Wi-fi in my phone settings
- In Goodtime app I turn on option 'Disable wi-fi' (When turning on this option no new permissions were asked to set.)
- I start new session
Expected result: Wi-fi is disabled
Actual result: Wi-fi is enabled
Device: Samsung A9.

**Comment by adrcotfas** [comment]
I cannot reproduce this on my devices. What Android version are you using?

**Comment by BorisB** [comment]
Android 9.
I noticed that it doesn't work in airplane mode only.
So first steps should look like:
- I turn on airplain mode
- I turn on Wi-Fi
- I start session and see that Wi-Fi was not disabled

ср, 8 янв. 2020 г. в 19:23, Adrian Cotfas <notifications@github.com>:

**Comment by brigio345** [comment]
```
setWifiEnabled(boolean enabled)
This method was deprecated in API level 29. Starting with Build.VERSION_CODES#Q, applications are not allowed to enable/disable Wi-Fi.
```

(From https://developer.android.com/reference/android/net/wifi/WifiManager.html#setWifiEnabled(boolean) )

**Comment by adrcotfas** [comment]
@brigio345 
Thanks for pointing this out!
I'll make the necessary changes to remove the "disable WiFi" option for users of >= API level 29.
