### ISSUE TITLE
Can't upgrade

### ISSUE THREAD

**Issue by BorisB** [adrcotfas/Goodtime#173]
Steps to reproduce:
- I Install app from Google Play (version 2.1.4)
- Select in menu "Upgrade"
- Display become clean empty for ~15 seconds
- I see button "Upgrade" and tap it
- In the button I see white area with loading circle ~30 seconds
Expected result: Purchase confirmation form
Actual result: I see message "No access to internet"
All other apps on device work with internet well.

**Comment by adrcotfas** [comment]
Is this behavior consistent on several tries?

**Comment by BorisB** [comment]
Just tried it and now it works. Thank you.

ср, 8 янв. 2020 г. в 19:23, Adrian Cotfas <notifications@github.com>:
