### ISSUE TITLE
Unable to start break from within an application

### ISSUE THREAD

**Issue by ngleb** [adrcotfas/Goodtime#174]
I'm not sure if this is expected, but if for some reason I didn't start break from notification area, I won't be able to do it from anywhere else.

When I open the app, there's only 25 mintues (i.e. work session) and I can't start a break.

Also, on Motorola G5S+ with stock Android 8.1, after a session finishes, screen turns on and all I see is 25 min (so no break again).

Is this expected? I might be doing something wrong, but it's not easy to test all possible variations when I have to wait 25/5 for each test. I'm using the version from GPlay and tried another version from FDroid. Both of them behave in the same way.

**Comment by adrcotfas** [comment]
There should be a "Session finished" dialog which cannot be canceled unless an action is taken, along with the notification. This does not appear on your device?
I cannot reproduce this behavior on my Samsung devices or inside an emulator.
The work and break durations are configurable from the settings, by the way.
To force a break, you can swipe left or right when a work session is in progress.

**Comment by ngleb** [comment]
Hi, sorry for the delay.

So I tested the app again, and do see the popup sometimes, but not always.

If a open the app, start the session and lock the screen w/o closing the application, then the screen is not locked (but it is off) and when the session is finished, screen is on and I see the popup.

If I lock the screen, then after session is finished, screen is on, app is visible with just 25 min on it and not popup (though there's a notification).

If I keep screen on and keep app open or return to main screen (so app is not visible), then I see popup all the time.

There's always a notification but there are times when I miss the button on popup or in notification and the break disappears. So I cannot start break from anywhere else. So the problem is actually only connected to break since it cannot be restarted from within the app itself, only via popup or notification.

**Comment by adrcotfas** [comment]
This was fixed and the start break dialog will not disappear anymore.
