### ISSUE TITLE
'Save custom profile' button not visible when entering session durations

### ISSUE THREAD

**Issue by leostewart** [adrcotfas/Goodtime#175]
When a user enters in a session duration instead of using the sliders, the 'Save custom profile' button does not appear. I think this may be a minor bug.

Steps to reproduce:
1. Navigate to Settings > Timer duration
2. Select an existing profile if not already active
3. Click the value next to either the 'Work session duration' or 'Break duration' sliders
4. Enter any number and click 'OK'

Observed behavior:
'Save custom profile' button is not visible and previously selected profile is still listed under 'Profile'

Expected behavior:
'Save custom profile' button should be visible and no profile should be listed under 'Profile'

![IMG_20200121_193816](https://user-images.githubusercontent.com/30129044/72855482-a5e84100-3c85-11ea-92f8-b0e437c9d498.jpg)

**Comment by adrcotfas** [comment]
Thanks! This will be fixed in the next release which will come soon.
