### ISSUE TITLE
[FR] Add gesture for reseting the timer

### ISSUE THREAD

**Issue by erazemkokot** [adrcotfas/Goodtime#176]
Just like swipe up adds one minute, something like a double/triple tap could reset the timer (different enough from other gestures to not be confusing).

Use case: When starting a new session and having to do something external in the first couple of minutes. This would allow the user to start the session again, without increasing the session counter, unlike skipping, which does increase it.

**Comment by adrcotfas** [comment]
It's already implemented. Swiping down will reset the timer.

**Comment by erazemkokot** [comment]
My bad, thanks :)
