### ISSUE TITLE
LED notifications not working?

### ISSUE THREAD

**Issue by afita** [adrcotfas/Goodtime#178]
On a Huawei Y6 (2017) with Android version 6.0 (patch level: August 5, 2018), the LED notifications don't seem to work: the LED doesn't light up when the time ends. I'm running with Vibration: None and Notification sound: off. Even with Vibration active, the LED doesn't light up.

**Comment by adrcotfas** [comment]
@afita Does this reproduce on other phones? I don't have any phones with LEDs at hand.

**Comment by afita** [comment]
I only have this Huawei Y6 at the moment. I'll test with other phones when I get the chance.

**Comment by adrcotfas** [comment]
This should be fixed with 4de9054d2b906c151f2a722f00aace01a0c9ddce.
Version 2.1.5 will be shortly available for beta testing on Google Play.

**Comment by afita** [comment]
I installed version 2.1.12 from F-droid and notifications are not working.

**Comment by adrcotfas** [comment]
You mean LED notifications, right?
Unfortunately I don't own a device with a notification LED.
Can someone else test this?

**Comment by afita** [comment]
I wanted to let you know that I installed Goodtime version 2.2.5 from F-Droid repository and the LED notifications work now (when the screen is closed).

I also noticed that when the screen is active there is the possibility to "Flash the screen" to get the humans' attention, which is very nice!

Thank you.

**Comment by Korb** [comment]
Yes, you can enable `Torch (A visual notification for silent environments)` (aka `LED Flash Notification` aka `Flash Notification`) and `Screen flash (A visual notification for silent environments)` in the app settings. This is great! 🥰
