### ISSUE TITLE
add a link to Pomodoro description in Readme.md?

### ISSUE THREAD

**Issue by k3b** [adrcotfas/Goodtime#179]
In a german podcast about "working at home in a distributed scrum team" i heard of the https://en.wikipedia.org/wiki/Pomodoro_Technique. After searching in f-droid i found your app on github.

Is it possible to add the keyword "Pomodoro" to the repository and  a wikipedia link to the Pomodoro methodology  https://en.wikipedia.org/wiki/Pomodoro_Technique in the readme.md that describes the priciples behind it?

Or are there any copyright trademark/restrictions that prevent it?

**Comment by adrcotfas** [comment]
Indeed, there are trademark restrictions for the words "Pomodoro Teechnique" and even "Pomodoro".

**Comment by k3b** [comment]
ok thanks for fast info
