### ISSUE TITLE
Implement a flashing notification

### ISSUE THREAD

**Issue by GjjvdBurg** [adrcotfas/Goodtime#183]
First of all, thanks so much for making this great app!

I use this app in the fullscreen mode with the screen on, so the phone shows a visual reminder that I'm on a timer. However because I usually work with headphones on, I don't hear the vibration notification (and can't use sound because it would disturb people around me). I was therefore wondering whether it would be possible to add a "flashing" notification option that would signal the time is up by inverting the colors of the screen repeatedly (so black text on white alternating with white text on black). This would be noticeable and wouldn't disturb the people around me.

Thanks in advance for considering!

**Comment by adrcotfas** [comment]
I'm glad that you like it!
Since 2.1.7. you can use your headphones as the notifications will act as regular notifications.
There is no sound output from the phone speaker when you have headphones connected.

**Comment by GjjvdBurg** [comment]
Thanks for the swift response! I guess I wasn't entirely clear, the headphones are connected to a computer, so I wouldn't be able to hear the notification from the phone (that's why I thought a visual notification might be cool). Thanks though!

**Comment by cord-otten** [comment]
Second the request. I love the app, but a visual notification would be great.

**Comment by adrcotfas** [comment]
@GjjvdBurg, @cord-otten In your opinion, would a flashing "session/break finished" dialog suffice or would it be more useful to flash the whole screen?

**Comment by GjjvdBurg** [comment]
To be honest I haven't used the app much lately, as my workflow has changed to time tracking using Toggl. I still think it's a great app though, and may return to it in the future. FWIW, I had in mind that the entire screen would flash by inverting the colors (so you'd still have the popup notification, but the background would repeatedly flash by changing the background color from dark to light etc). I don't know how feasible that is though.

**Comment by adrcotfas** [comment]
This was implemented and will come in the future release on F-Droid and Google Play.

**Comment by GjjvdBurg** [comment]
That's awesome, thank you!
