### ISSUE TITLE
Adding a stop/close option

### ISSUE THREAD

**Issue by linguoguo** [adrcotfas/Goodtime#184]
First of all, thank you for this app! I'm using it everyday.

However, I noticed that when I finished a task and wanted to take my break, or during a break I skiped the session,  the current session was not saved in the statistics.

It would be cool if you could add a stop option, like a double-click to close a session, or a break.

**Comment by adrcotfas** [comment]
What version are you using?
To stop a session you can swipe down on the timer.

**Comment by linguoguo** [comment]
Hey,
I'm using the version 2.9.1
Here's a video to be more  explicite:
I'm at the end of the session 3( 16 minutes remaining) and I want to jump
to session 4, i swipe down, the counter of the sessions is still 3 while
i'm at the 4th session.

I hope it's clearer  :p


Le mer. 15 avr. 2020 à 21:23, Adrian Cotfas <notifications@github.com> a
écrit :

**Comment by adrcotfas** [comment]
I think you mean 2.1.9.
Was the counter 2 before you stopped session 3?
Was the counter 3 after you stopped session 3?
If yes, I see no problem. The counter will increment after a session of at least 30+ seconds(considered as the minimum of 1 minute) is finished/ stopped or skipped.

**Comment by linguoguo** [comment]
Yes, I mean 2.1.9.

Oh yeah, I see, the counter increments when I swipe right !

Thank you for your attention.

**Comment by adrcotfas** [comment]
@linguoguo Doesn't it increment when you swipe down too? I mean with a session of at least 30+ seconds.

**Comment by linguoguo** [comment]
No it doesn't work when swipe down even with a session of 30 minutes, but
it works whrn swipe right.

Le jeu. 16 avr. 2020 à 21:58, Adrian Cotfas <notifications@github.com> a
écrit :

**Comment by adrcotfas** [comment]
The fact that the session was not stored to the statistics on stop was a bug. It was fixed in the last version.

**Comment by linguoguo** [comment]
Wow I'll get the new version right now.

Le mer. 22 avr. 2020 à 20:55, Adrian Cotfas <notifications@github.com> a
écrit :
