### ISSUE TITLE
Make Alarm Sound Once or Continuously

### ISSUE THREAD

**Issue by r4taw2mg** [adrcotfas/Goodtime#186]
I would like to have a setting, to either repeat an end-of-pomodoro-alarm once (or a configurable number of times) or to sound it continously.

Maybe this is just a misunderstanding. There is one option "Override sound profile" which I understood as playing the alarms as an alarm (own volumne, possibly not regarding DND setting). Does it also set the alarm to be played continously?

**Comment by adrcotfas** [comment]
There's already an option for this called "Insistent notification".
