### ISSUE TITLE
Use system do not disturb mode?

### ISSUE THREAD

**Issue by reox** [adrcotfas/Goodtime#188]
This is more a question than a bug.

I think since some versions of Android (maybe 7?) there is this new DnD mode. If I enable it, it shows me the DnD icon ( :no_entry: ). Since Lollipop you had the option to switch to the DnD mode I think, but some time ago that got changed again...

If I configure Goodtime to use the DnD mode it only switches to silent mode but seems to not trigger the DnD mode. I can see the silent mode icon, but not the DnD icon. Basically both does the same thing - however you can also configure to do not show the LED in the system DnD mode, which is still active when Goodtime is running.
So, I wonder what kind of mode Goodtime is using here or if this other mode is something different?

**Comment by adrcotfas** [comment]
Goodtime changes the sound profile to mute and does not toggle the DnD mode from Android.

**Comment by Korb** [comment]
/dup #102?

> Goodtime changes the sound profile to mute

Is this a configurable setting that automatically activates during the work phase?
