### ISSUE TITLE
Handle notifications during a call

### ISSUE THREAD

**Issue by BashBBQ** [adrcotfas/Goodtime#189]
I always use headphone when I work.
When I'm in a voicecall and a timer ends, the voice switches from headphone to speakerphone.

**Comment by adrcotfas** [comment]
What version are you using?

**Comment by BashBBQ** [comment]
Hi,
It's 2.1.11 from Play Store.

**Comment by adrcotfas** [comment]
Do you have the "Override sound profile" option on?

**Comment by BashBBQ** [comment]
IT's OFF.

**Comment by adrcotfas** [comment]
Indeed, I managed to reproduce this bug.

**Comment by KopiasCsaba** [comment]
It's affecting me too, just +1!
