### ISSUE TITLE
It apears that Goodtime skips the long break after 12 sessions

### ISSUE THREAD

**Issue by ThracianKnight1907** [adrcotfas/Goodtime#190]
First off, I want to thank you for this app. It's very clean, nice and is foss.

However, I noticed what appears to be a bug. I just finished my 12th session and I got a 5 min break (instead of a 15-minute one). The small cup of coffee says that 12 sessions are completed. I don't think the 8th was skipped.

**Comment by adrcotfas** [comment]
I'm glad you like it!
It may be the expected behavior. The "sessions until a long break" counter is reset if you don't complete the work session after <work session duration> + <break session duration> + 20 minutes from the previous completed work session.
Was this the case?

**Comment by ThracianKnight1907** [comment]
Yes, that was probably the case. Maybe there should be a warning/info in the app settings? I looked but I didn't see anything related to this

**Comment by adrcotfas** [comment]
I should find a way to make this transparent to the users.

**Comment by ngleb** [comment]
Are there any other conditions for this? Is it possible to disable this behaviour at all?

I once finished working with 7 session one day and on the next day long break was enabled after 3 work sessions, while in Settings I have setup 4 work sessions before the long breaks.

**Comment by adrcotfas** [comment]
@ngleb: Can you provide a screenshot from the statistics list page?
This should not happen because the counter is reset after a certain amount of time(see my previous comment). Perhaps you skipped a work session? This would count for the long break counter.

**Comment by ngleb** [comment]
@adrcotfas Sure, here it is:
![scr](https://user-images.githubusercontent.com/46774/83064270-b8d3ad80-a08b-11ea-8e8c-3c2058ec4480.png)

Sometimes I need to work longer or may forget to start break. I try not to make breaks longer except when long break is not started, but was expected. If there's a separate timer that resets long break session count, then it's really hard to keep tracking these sessions as timer has stopped and there are no other timers or any other indicators.

Personally, I would prefer to have nothing except for 25/5 minutes.

I can think of another feature: keep timer running. For example, 25 minutes passed and break is not started for more than 30 seconds. At this point another timer should appear and should keep running until next break is started. The idea is to account time between the sessions, but obviously it completely breaks the idea of 25/5 sessions.

**Comment by adrcotfas** [comment]
`Personally, I would prefer to have nothing except for 25/5 minutes.`
You can disable long breaks from the settings.

**Comment by ngleb** [comment]
> You can disable long breaks from the settings.

Yes, I know that :-) I meant that I would prefer `work session duration` + `break (or long break) session duration` but not hidden `20 minutes` because it is hard to keep track of this.
