### ISSUE TITLE
UI redesign

### ISSUE THREAD

**Issue by sudhirkhanger** [adrcotfas/Goodtime#191]
**I have some redesign ideas to improve Goodtime.**

1. Overflow menu is typically used to display a menu. Goodtime uses it for letting a user select a label. IMHO I keep using it how I would use overflow menu in rest of the Android environment to open a menu. And inside the statistics a different icon is being used for labels.
2. I should be able to see a the labels and their number of pomodoro completed.
3. The bottom bar may possibly let me go to statistics directly.

**Some possible suggestions from my side.**

1. Use same icon for labels.
2. What about if we use an Exposed Dropdown list instead of a dialog? This would not require much hand movement.
3. Statistics button in the bottom bar.
4. Display label at the top of the timer.
5. Display x number of label stats in bottom.

Maybe we could hide these in full screen and display when a user clicks on the screen. Maybe we could display this permanently in the non-full-screen view in case user wants to see it.

If you think these ideas are something you would be willing to incorporate then I can try to find some time to send pull requests.

**Comment by adrcotfas** [comment]
I appreciate your intention to improve the UI!
It would be nice to see some mock-ups before deciding anything. I would like to keep it as simple as possible on the main screen.

**Comment by matrixik** [comment]
I would like to see visual timer like in "Visual Timer - Countdown" app. You need to select in option to always start from full circle.

![Screenshot_2020-05-26-21-25-25-875_at cwiesner android visualtimer](https://user-images.githubusercontent.com/201930/82941918-7d57b700-9f97-11ea-8455-aee81547ae9c.jpg)

Using color of label. I believe it's quite simple :)

And +1 for "Display label at the top of the timer."

**Comment by adrcotfas** [comment]
@matrixik This would defeat the purpose of having it battery friendly while the screen is on. I don't want to go into that direction.

**Comment by matrixik** [comment]
Too bad, personally I don't care about battery because I use second phone (I bought one with broken back for dirty cheap) for timer that stay always next to my computer (no sim card in, almost everything turned off, airplane mode etc., charging cable always next to it, IPS screen so I don't think that black background is helping). I would be using "Visual Timer - Countdown" because I prefer it visually but it doesn't have history/statistics and only red color for circle.

I was surprised that beside `Goodtime` I could not find any timer app with history that have minimalist UI (without dozen of unnecessary icons when timer is running). Thank you for that.

**Comment by matrixik** [comment]
I used app for some time and started to be irritated by slow process of changing labels for work time. Now after brake you need to start new work or cancel then click menu on right side and then click again to select desired label. I think it would be faster to show labels to choose from at screen after break end (with last used label on top). Then user could immediately start new work with one click on desired label. 

I created mock-up (with the power of paint)
![Screenshot_20200529-142855~2](https://user-images.githubusercontent.com/201930/83260671-778deb80-a1ba-11ea-9b53-75d7d9e80b04.png)

What do you think?

**Comment by adrcotfas** [comment]
You can change the label anytime during the work session. It would take 3 taps.
My concern here would be adding new UI elements which will be used only by a few users.
At the moment, the dialog is equivalent in functionality with the notification that comes at the end of a session. Modifying the notification to select a recent label is not something I want to do.
