### ISSUE TITLE
Add screenshots on F-Droid

### ISSUE THREAD

**Issue by ahangarha** [adrcotfas/Goodtime#194]
Screenshots are missing on F-Droid.

As I see, `fastlane` directory is missing in the repo. should I make it?

**Comment by adrcotfas** [comment]
I'm not familiar with `fastlane`. Can you give more details?

**Comment by ahangarha** [comment]
https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by adrcotfas** [comment]
I would prefer to have the screenshots directly in the F-Droid repo.  
I'll create a MR for this later.

**Comment by ahangarha** [comment]
As long as it shares screenshots, what ever you do is good :)

در تاریخ چهارشنبه ۲۰ مهٔ ۲۰۲۰،‏ ۱۲:۴۰ Adrian Cotfas <
notifications@github.com> نوشت:

**Comment by not-programmer98** [comment]
Any updates?
