### ISSUE TITLE
Cannot choose default sounds since update

### ISSUE THREAD

**Issue by natrius** [adrcotfas/Goodtime#195]
Device: Xiaomi Mi 9 (MIUI battery optimizer disabled)
Android: 10
App Version: 2.1.1.14

Since the last update (via F-Droid) the sounds are gone (no audio) and with "Finished work notification" i can choose between "Default notification sound", "ring.ogg" and "Add ringtone" but i cannot choose anymore from the other sounds i was able before. 

EDIT: An when choosing ring.ogg it does not stop again. Have to kill the app. 
EDIT2: Actually, that was my own fault. Hit the "use as ringtone" by mistake.

**Comment by adrcotfas** [comment]
@natrius Is this still a problem for you?

**Comment by natrius** [comment]
Tried now: 
2.1.13 - Options - Settings - "Finished break notofication" - can choose a song from my smartphone. 
Update via F-Droid:
2.1.14 - Options - Settings - "Finished break notification" - can choose a song from my smartphone. 

Don't ask me why its working right now o.O
If it should happen again, i will reopen the issue. Thanks for your work :)
