### ISSUE TITLE
Compatibility issues on the dot in the timer

### ISSUE THREAD

**Issue by john2020star** [adrcotfas/Goodtime#197]
Hi

I found a compatibility issue on the dot in the timer of MainActivity.

API 21
<img width="284" alt="image" src="https://user-images.githubusercontent.com/62385383/84781801-dad0a800-b019-11ea-989e-0b87e542e765.png">

API 22
<img width="348" alt="image" src="https://user-images.githubusercontent.com/62385383/84781831-e3c17980-b019-11ea-89f3-a58c8e065f92.png">

The root cause you can refer to https://stackoverflow.com/questions/27384655/android-gradient-on-lollipop-not-working-api-21.

Thanks for your attention.

**Comment by adrcotfas** [comment]
Fixed in 2.1.15
