### ISSUE TITLE
Add an option to extend the time after a work/break has ended

### ISSUE THREAD

**Issue by sandorex** [adrcotfas/Goodtime#198]
Currently it shows two options `CLOSE` and `START WORK/BREAK`, it would be helpful to add another option like `EXTEND` or `POSTPONE` that will allow to add more time

**Comment by adrcotfas** [comment]
I plan to add an option to notify the user 1 or n minutes before the end to give the change to manually extend how long each user wants to instead.
Does that sound ok for you?

**Comment by sandorex** [comment]
Sounds great!

**Comment by sandorex** [comment]
What happend to this?

**Comment by Korb** [comment]
> Press the "+".

I pressed it, but the flash keeps blinking and the beep keeps sounding:

https://github.com/user-attachments/assets/229d0b34-7ef6-4918-a1ef-4bc79ec8b7e9
