### ISSUE TITLE
timer status in the status bar and the notification drawer

### ISSUE THREAD

**Issue by adrcotfas** [adrcotfas/Goodtime#2]
- display the remaining minutes

**Comment by adrcotfas** [comment]
also include buttons for pause/resume and stop in the notification

**Comment by wolfgang42** [comment]
I just had a go at implementing this; here's a dump of what I've discovered so you don't have to re-discover all this.

The most obvious way to do it is [NotificationBuilder.&#8203;setUsesChronometer()] (https://developer.android.com/reference/android/app/Notification.Builder.html#setUsesChronometer(boolean)), which makes the `when` field display a counter. Then it would be a simple matter of making `.setWhen()` the time that the countdown will end. Unfortunately, in Android prior to API 24, the countdown doesn't display properly (on my phone it says '`0:-1234`'; older versions may [display strange symbols](https://code.google.com/p/android/issues/detail?id=57199)). API 24 added [setChronometerCountDown()](https://developer.android.com/reference/android/app/Notification.Builder.html#setChronometerCountDown(boolean)) which makes the timer go in the other direction, but as far as I'm aware there aren't *any* other phones other than the Nexus for which Nougat is available yet.

**Comment by adrcotfas** [comment]
Thanks, I'll have a look when I find some spare time.
I was thinking of a more CPU friendly solution updating once a minute, not continuously and displaying only the minutes left.

**Comment by wolfgang42** [comment]
I think that the Chronometer can tell when the notification is being displayed (because it's part of the Android OS) so it doesn't take up extra CPU time. Since that's not going to work I agree that only updating the notification once per minute is the best solution.

**Comment by adrcotfas** [comment]
Fixed with #49 (except the notification bar part).
