### ISSUE TITLE
 Code Quality Analysis

### ISSUE THREAD

**Issue by terilias** [adrcotfas/Goodtime#201]
Hello there!
I did a quality code analysis for your project and I would like to share the results of this analysis here. The analysis was mainly done using the SonarCube tool which is responsible for locating code smells and measuring other  metrics for quality in the project. I also used the monkey tool in Android Studio to find errors that could occur when the user interacts with the application, but the test did not detect problems.
I attach two PDF files: the first includes an overview of the analysis and the second a report with more detailed information. These files were created by a trial version of a SonarQube plugin (sending results to GitHub is not included in the free version of SonarQube).
I know time is limited and valuable to developers, so  if you don't have time and you want to improve reliability level of the project  , I would recommend correcting errors that fall into the category of Blocker and Critical. They are the most important for the application. (For more information on how  SonarQube classificates the bugs, [visit this page](https://docs.sonarqube.org/latest/user-guide/issues/)).
 If these errors are corrected, the reliability level will increase significantly.
Screen snapshot of errors are attached .
![7bugs](https://user-images.githubusercontent.com/37142366/85315575-faf1e280-b4c3-11ea-8a43-0d225e7fa1eb.png)
Project's security is at a very good level.
In addition, there are 346 code smells. Code smells are very important in open source projects because maintainability is directly related to them.
For a detailed analysis and to be able to see code smells, please install SonarQube locally and let me know if I can help.  
A very good tutorial on the installation and use of SonarQube at Android Studio which I followed can be found [here.](https://android.jlelse.eu/have-code-quality-analysis-in-your-android-project-2a549e04d1a8)
Thanks for your time!
[Analysis Overview.pdf](https://github.com/adrcotfas/Goodtime/files/4814606/Analysis.Overview.pdf)
[Report for Quality Analysis.pdf](https://github.com/adrcotfas/Goodtime/files/4814607/Report.for.Quality.Analysis.pdf)

**Comment by adrcotfas** [comment]
This is not relevant anymore as the app was converted to Kotlin.
