### ISSUE TITLE
Quit / Exit is not obvious

### ISSUE THREAD

**Issue by daniel-barrows** [adrcotfas/Goodtime#202]
I briefly tried this app, but couldn't figure out how to turn it off. No button or option was apparent in the app. I can pause it. Closing the notification isn't possible. Closing the app doesn't work.

I immediately uninstalled the app to resolve the issue. I suspect there is a way to do this that I couldn't figure out, but I recommend making it more obvious for future users so they don't have the same response that I did.

**Comment by Kashish-Sharma** [comment]
I'm not sure but if you're asking to reset the timer (reset the session), you can just pause it and increase the minutes by swiping down as many times as you like (this is explained pretty well in the intro tutorial).

**Comment by adrcotfas** [comment]
@daniel-barrows Have you tried swiping down on the timer?
