### ISSUE TITLE
Show hour count for labels

### ISSUE THREAD

**Issue by JPinSPACE** [adrcotfas/Goodtime#203]
On the Statistics page, Goodtime shows the percentage of time spent on each label for the selected time period. It would be helpful to break this into a list of labels and the number of hours spent on each label. Currently, the user can achieve this by simply multiplying the percentages against the total time or by using the CSV export, but having it available at a glance would be great.

Thanks for all your hard work on this excellent app.

**Comment by adrcotfas** [comment]
Thanks for your suggestion!
This was implemented and will come soon in 2.1.18 as default. The users could toggle between percentages or duration by clicking on the pie chart.

**Comment by JPinSPACE** [comment]
Great! Thanks again. This app has had a surprisingly large positive impact on my life.
