### ISSUE TITLE
Pre-notification with insistent notification keeps on notifying for 1 minute with no way to stop it.

### ISSUE THREAD

**Issue by samyak039** [adrcotfas/Goodtime#205]
When enabled both of the options, **pre-notification** and **insistent notification**, the pre-notification also becomes insistent and when the pre-notification kicks in there is no way to dismiss it, and it will keep on notifying for the complete 1 minute (that's the time gap between pre-notification and notification for break or work) with no way to stop or dismiss it.

So these are my suggestions to handle this:  
- to pre-notify only once even if insistent notification is turned on (but that would defy the purpose of insistent notification)
- to provide a way to stop the pre-notification (this seems to be the legit one)

**Comment by adrcotfas** [comment]
Thanks for your feedback!  This is bug is valid for the vibrations only; It should pre-notify only once. For the sake of simplicity I did not add any notifications/ dialogs for this pre-notification so I'll keep it like this.
A fix will come soon.

**Comment by samyak039** [comment]
Thanks :)

v2.2.2 fixed it.
