### ISSUE TITLE
More clear indication whether a work session or break is active

### ISSUE THREAD

**Issue by chrkuhlmann** [adrcotfas/Goodtime#208]
First of all thanks for this great timer app.

With v2.2.2 the small indicator at the bottom of the screen is gone and the only indication whether I should be working or be on a break is the very tiny icon in the Android status bar.
I'd like to have an option to show the icon at the bottom of the screen or have another clearly visible and large indicator like timer color or a symbol before the timer count that shows the work/break state. There's no point in having a large timer countdown if you don't know what it is counting (happens to me all the time after I had to leave the room to go to the printer and was interrupted). Having to pick up the phone just to be able to determine the state is not optimal and distracts.
Please consider an option for this. Thanks.

**Comment by adrcotfas** [comment]
I removed the indicator in v2.2.0 since it's redundant with two other views: the notification icon you mentioned and the timer color which is gray for a break session and white or colored according to the label for a work session.
Hopefully this is not a big deal for you.

**Comment by chrkuhlmann** [comment]
Hi, thanks for the quick response.
I think that the timer color could work for me, but for this it needs to change or be configurable. The gray is really much too close to the white for me. Especially if the environment is bright, it is hard to tell gray and white apart. I still think that an optional symbol above or below the timer would be best, but choosing another color for breaks (e.g. red or green) or making it configurable could also work.
