### ISSUE TITLE
Unable to select custom ringtone for notification sounds

### ISSUE THREAD

**Issue by JPinSPACE** [adrcotfas/Goodtime#210]
When I try to select "Add ringtone" for the "Finished work/break notification" sounds a message pops up reading "Unable to add custom ringtone"

I've tried both .mp3 and .wav.

For a little extra context, I was only trying to add a custom ringtone as a way to add a brief pause between notification sounds when using "Insistent notification". Since none of my phone's built-in ringtones have extra silence and there is no pause between notifications, it has the irritating effect of rapidly playing the notification in succession until I can stop it. Adding an optional pause between notification sounds would be great if addressing this custom ringtone issue is too tricky.

Phone: Galaxy XCover Pro
Goodtime version: 2.2.4
Android version: 10

Thanks for all your hard work on this excellent app.

**Comment by adrcotfas** [comment]
The fact that you cannot add a custom ringtone, is a limitation of the library I use for that. There's an open bug here:
https://github.com/Gericop/Android-Support-Preference-V7-Fix/issues/203

**Comment by JPinSPACE** [comment]
Ahh makes sense. No sweat then. If you were to consider adding a brief pause between each playback in insistent mode I'd appreciate it, but it's not exactly critical. Thanks again!

**Comment by adrcotfas** [comment]
This was fixed on https://github.com/adrcotfas/Goodtime/tree/v3  and will come in the next version.

**Comment by yatpay** [comment]
Great, thank you! I really appreciate your work on this app. I use it for dozens of hours a month and find it incredibly helpful
