### ISSUE TITLE
Phone clock freezing

### ISSUE THREAD

**Issue by johnniehard** [adrcotfas/Goodtime#211]
I've had this problem a couple of times the past few days. When having a timer running the phone clock in the upper left corner freezes and stops showing the current time, the Goodtime timer is still running. Is this a known issue? Didn't find anything searching in previous issues.

I can provide more info if necessary.

**Comment by adrcotfas** [comment]
You mean the system clock stops showing the current time? That doesn't sound like it has anything to do with the app.

**Comment by johnniehard** [comment]
I guess so, but the problem has only occurred while using Goodtime. I'll get back if it happens again and I can provide more details.
