### ISSUE TITLE
[FeatureRequest] Dynamic Session Length

### ISSUE THREAD

**Issue by Redunca** [adrcotfas/Goodtime#215]
I'd like to propose a new feature here.

For now, I've created 4 differents profiles depending on day of week and AM/PM because i need to have sessions and pause of differents length to accomodate with my work schedule.

I'd like to be able to define work time and let the app manage sessions length and pauses.

For exemple :
Profile = workday
Time Periods:
1- 09:00 AM to 12:15 AM (3 work sessions)
2- 01:30 AM to 06:00 PM (4 work sessions)

And the app will automatically setup sessions as 57/12 for morning, long break of 75 then 60/10 for afternoon.

What would be awesome is that, instead of pausing the timer when time's up, it would keep counting overtime so when i finally end the work session, the reminder of the day can be adapted to fit the rest of the day properly and ensure i end at 6PM

If you like the idea, i can eventually get around to propose some code for it (native android is not my forte but i should manage)

**Comment by adrcotfas** [comment]
Thank you for your proposal! 
That's a quite specific feature request and I would avoid to such a feature because I want to keep the app as simple as possible. I think that a small minority of users would use something like this.
