### ISSUE TITLE
"Minutes only" no clear clue that the countdown started

### ISSUE THREAD

**Issue by oluc** [adrcotfas/Goodtime#218]
when using with "Minutes only", there's no real clear clue that the count actually started

- black screen displaying "25"
- taping "25"
- the countdown starts, 
  although there's no reall clue that it actually did
  the screen still display "25" as the countdown runs "24:59" and so on

it's confusing.

(maybe you could display something when the countdown is not running, that would vanish when it starts.
maybe just a string like "tap to start", or should it display "24", or something else?)

**Comment by adrcotfas** [comment]
The notification icon will appear in the top left when starting a session. That's how you can check if the session is active.

**Comment by oluc** [comment]
right, but not in fullscreen mode.

(I'd like to use it in the most minimalistic way, with no distraction : no seconds counting, no notifications, just the minutes.)

**Comment by adrcotfas** [comment]
Here's a solution: In fullscreen mode, touch the screen once to reveal the top bar with the notification icon and it will automatically hide.
Sorry but I don't plan to change this at the moment but you could do it yourself if you want to and use a custom build of Goodtime.
