### ISSUE TITLE
Feature request: Todoist integration

### ISSUE THREAD

**Issue by StoppingBuck** [adrcotfas/Goodtime#224]
Hey, it seems that the app PomoDone - which has a similar scope to Goodtime - is offering [integration with Todoist projects](https://todoist.com/integrations/apps/pomodone) likely using the [Todoist API](https://developer.todoist.com/).

It could be interesting to have something similar for Goodtime, so I'm creating this issue in case anyone wants to attempt such a thing. I might even take a crack at it myself at some point.

**Comment by chrissssss** [comment]
@StoppingBuck Do you mean something like having tasks appear as a label in the app? Synchronization could filter for a todoist label or something. Backwards sync could also update the todoist task with custom comment that xyz has worked time x on the task

Dependencies on todoist task structure like hierarchic tasks should not be in the scope at first hand
