### ISSUE TITLE
[Feature Request] Add time manually in stats

### ISSUE THREAD

**Issue by ClementDelannoySlateDigital** [adrcotfas/Goodtime#226]
Hi and thanks for your app :)
May be I'm the only one but sometimes I'd like to manually add time/sessions to my stats. 
It is useful for me because often I don't launch a session, either because I don't have my phone or I can't use it, or I forgot ... but I still want to add this time so I can monitor my work duration.

I will try to think about a nice way to integrate that if that can match with other feature integration, don't hesitate to contact me if you are interested.

Thanks again, have a nice day :)

**Comment by silktrader** [comment]
Perhaps I misunderstand your intentions, but I think it's possible to add sessions manually by going in "Statistics", hitting the "+" button in the top bar, describing the session (time, date, duration, label) and hitting "save".

**Comment by ClementDelannoySlateDigital** [comment]
Ho yes, so sorry, I missed that one ! 
Thanks :)
