### ISSUE TITLE
[Feature Request] : white noise

### ISSUE THREAD

**Issue by rzasharifi** [adrcotfas/Goodtime#229]
If it possible add some white noise. If you combine this app https://github.com/ashutoshgngwr/noice with Good Time it will be more useful.

**Comment by wisp3rwind** [comment]
I use the same two apps in combination myself, but I don't think either of them should implement features from the other. Rather, I see more value in each app focusing on doing one thing well.

**Comment by d42** [comment]
I myself would quite enjoy feature like this, mostly to have a feedback that i'm still in session :3

**Comment by adrcotfas** [comment]
Thanks for your proposal but I'll keep the app as minimalistic as possible. I think this feature would be enjoyed by a minority of users.
