### ISSUE TITLE
mention contributors in the about page

### ISSUE THREAD

**Issue by adrcotfas** [adrcotfas/Goodtime#23]

**Comment by adrcotfas** [comment]
Commit: https://github.com/adrcotfas/Goodtime/commit/d5036f1da8443e205246a3d9ec27c4e3339175a9
Waiting for feedback before closing.

**Comment by wolfgang42** [comment]
Can you make it 'Wolfgang Faust' instead? (I also updated my GitHub profile to match.) Other than that it looks good to me.

**Comment by adrcotfas** [comment]
Commit: 87ae442e23d35ead1bcffed8d1cb1fb24513d112
