### ISSUE TITLE
Starting next timer from notification does not clear prompt in app

### ISSUE THREAD

**Issue by emiham** [adrcotfas/Goodtime#230]
If you're outside the app and start the next timer from the notification pulldown, the next time you open the app there's still a prompt to start/cancel. If you choose start from there it pauses the current timer.

**Comment by adrcotfas** [comment]
I'm not able to reproduce this. Can you please provide a video?

**Comment by emiham** [comment]
Hopefully this explains it. 

https://user-images.githubusercontent.com/65129819/106644495-79028580-658b-11eb-853d-6f4d35f97089.mp4

**Comment by adrcotfas** [comment]
What device and Android version are you using?

**Comment by emiham** [comment]
OnePlus 6, Android 10 (OxygenOS 10.3.7).
