### ISSUE TITLE
Feature request: Show current tag on main screen

### ISSUE THREAD

**Issue by wisp3rwind** [adrcotfas/Goodtime#235]
As the title says, I would appreciate if the currently selected label could be shown on the main screen. What happens fairly often right now is that I have some other label selected from previous sessions, and forget to change it when starting to work on something new. Moreover, two taps are required to check what the current label is (once to open the label chooser, once to return to the main screen).

There's probably a balance to strike here between the minimalist design and adding more content to this screen. In this case, I'd personally say that the benefit justifies the change, hopefully it can be considered. Thanks!

**Comment by adrcotfas** [comment]
Hi,
The feature is already there. "View current label" in the Settings which is disabled by default.
Does this help?

**Comment by wisp3rwind** [comment]
Oops, yes, that's exactly what I meant :+1: Sorry for the noise here, I should definitely check out the settings in detail before requesting any other feature!
