### ISSUE TITLE
Manually typing the time of a session is not saved

### ISSUE THREAD

**Issue by spagy** [adrcotfas/Goodtime#236]
Heya, really appreciate the app!

Not sure I've described the issue well in the title but here is how to recreate it:

Got to the Statistics page
Tap the plus to add a new session.
Tap on the time to set a custom time.
Tap on the hour (or minute) to type in a the desired time.
While the cursor is still in the input field, tap OK.

Expect outcome: the value that was typed in the input field is saved
Actual outcome: the value before the input field was edited remains

**Comment by adrcotfas** [comment]
There's a Save button part of the bottom sheet dialog. Do you tap on it?

**Comment by spagy** [comment]
Ah sorry, I'm not sure I'm being clear.

The problem occurs before hitting the save button.

I type in my desired time then I tap OK. At this point the sheet dialog doesn't display the right time.

For example say the session has the time 10:00 and I would like to change this to 11:30.
I tap where it says 10:00 on the card.
This brings up the time selection dialog.
If I scroll to 11:30 and tap OK there is no issue.
If I instead I tap in the hour input field and type 11 then I tap in the minute input field and type 30 then finally press OK, the time will be changed to 11:00.
The issue is that the last input field that is changed before tapping OK is not saved (maybe registered is a better word).
I now have the opportunity to press save however this will save the session with the associated time of 11:00 instead of the desired time of 11:30.

Another solution is to type the hour, then type the minute then tap back in the hour input (but don't change it) this seems to save the minute input. Then finally tap OK.

Hope that explains the situation better.

**Comment by adrcotfas** [comment]
Indeed, this is a bug. Thanks!
I need to replace those dialogs. UI improvements will come.

**Comment by spagy** [comment]
Thanks for the confirmation and speedy responses! It's super helpful :)

**Comment by adrcotfas** [comment]
It should be fine starting from version 2.5.0 because I changed the dialogs.
