### ISSUE TITLE
Disable sound notifications when system Do Not Disturb mode is on

### ISSUE THREAD

**Issue by ngleb** [adrcotfas/Goodtime#240]
Hi!

I'm using Goodtime on Samsung phone with Do Not Disturb mode after 10 pm. I tried adding Goodtime to exception list in the device settings, so I get notifications when Do Not Distrub mode is on. But these notifications are with sound.

Is it possible to not produce any sound when system Do Not Disturb mode is ON?

**Comment by adrcotfas** [comment]
You could disable the notification sound from the app settings or put the phone on vibrate, assuming you didn't enable the "override sound profile" option.
