### ISSUE TITLE
How about a 5-More-Minutes button?

### ISSUE THREAD

**Issue by Krystofido** [adrcotfas/Goodtime#241]
No, I'm not mistaking this app for an alarm clock ;D
Sometimes the timer may be over, but I am definetely not. So how about an option to add a little more time to the session if it has ended?
That's not really a big issue since you can start a new session and end it a little earlier if you want, it still will add up to the statistics (Please don't ever change this!!! I love this app, because it allows to stop a sesssion earlier without losing the progress!). Still it would be a pretty cool gimmick.

**Comment by adrcotfas** [comment]
You could get the same benefit from using the "Pre-notification" which reminds you that the work session will soon end and swipe up for as many more extra minutes you would like.  
I was actually thinking of changing the saving to statistics part of incomplete sessions - making it an option.

Does this help?

**Comment by adrcotfas** [comment]
You could get the same benefit from using the "Pre-notification" which reminds you that the work session will soon end and swipe up for as many more extra minutes you would like.  
I was actually thinking of changing the saving to statistics part of incomplete sessions - making it an option.

Does this help?

**Comment by Krystofido** [comment]
Sure, I'm fully aware of this warning-option. But sometimes I just miss it anyway. Plus I'm not sure, but sometimes I just don't get a notification (yes I did turn off the battery optimization for this app). In the end 5-More-Minutes is just a cool idea I wanted to share with you, the app itself works perfectly fine.

But **PLEASE**, if you really want to remove saving statistics of incomplete sessions, make it optional, so that it can be turned on and off. It's always a big shame when apps make this kind of "upgrades", by completely removing some other good old functions :/
Anyway keep up the great work!
