### ISSUE TITLE
[Feature request] Suggest Longer Break after 4 Sessions

### ISSUE THREAD

**Issue by duesseldorferjung** [adrcotfas/Goodtime#244]
Big fan of the software thanks a lot for the effort!!!!

I do experience that after a couple of session I have a need for a longer break. 
It is also suggested as by the wikipedia article https://en.wikipedia.org/wiki/Pomodoro_Technique to have a longer break after 4 sessions. 
Can this be somehow integrated the popup after 4 sessions suggests  a 25min break?

**Comment by adrcotfas** [comment]
Thanks!
The feature is already there but you need to enable it from the Settings -> Timer Duration section.
