### ISSUE TITLE
F-droid behind by two versions

### ISSUE THREAD

**Issue by Thewisem** [adrcotfas/Goodtime#248]
Could you update your fdroid app. Its outdated by 2 versions

**Comment by adrcotfas** [comment]
It should be available soon since I created the release for 2.2.8. 22 hours ago.

**Comment by sprlptr48** [comment]
Do not know if it is right to ask here but, the F-droid version still isn't updated to 2.2.8, it is in the 2.2.7 version. Are you going to update it or did i not saw something i'm supposed to see?

**Comment by adrcotfas** [comment]
I forgot to modify the version string in gradle but the version is the latest.  
https://github.com/adrcotfas/Goodtime/blob/fef064f3d8798de6a189c2cb249fe413b591b39b/app/build.gradle#L15
I'll fix this with the next release!
