### ISSUE TITLE
implement notification played on headphones only if connected

### ISSUE THREAD

**Issue by adrcotfas** [adrcotfas/Goodtime#25]

**Comment by zanona** [comment]
Hey, @adrcotfas just reaching out to ask if there's any specific option to enable this under preferences as I am getting notification sounds played on both speaker and headphones?
Thank you.

**Comment by adrcotfas** [comment]
Hi, @zanona
this is not supported yet.

**Comment by zanona** [comment]
Oh sorry, I didn't see the issues was still open. 🤦🏻‍♂️ Thanks

**Comment by adrcotfas** [comment]
This was implemented in version 2.1.5.

**Comment by zanona** [comment]
@adrcotfas by any chance is this compatible with Bluetooth headphones?
I am having an issue where when the alarm sounds, it disables the sound on my BT headphones and uses the phone speaker instead. If I'm listening to Spotify, for example, the music will then only play on the phone speakers until I quit Goodtime.
