### ISSUE TITLE
Feature request: option to enable Focus Mode during work session

### ISSUE THREAD

**Issue by tjhleeds** [adrcotfas/Goodtime#250]
I love that the app can enable Do Not Disturb mode during a work session and disable it again when the session ends. It would be great to have the same functionality for a selected Focus Mode too (or instead). (To avoid any confusion, I'm referring to the Focus Mode functionality within the Digital Wellbeing controls.) 

The key benefit of this for me would be that it would disable all apps which aren't permitted during the selected Focus Mode. This is something I would be willing to pay for as a premium feature, but I don't know how much effort it would be to implement.

(For reference, I'm using a Samsung Galaxy A10 on Android 10.)

**Comment by adrcotfas** [comment]
This is something I would like too but unfortunately there is no API from Google to access the Focus Mode from 3rd party apps like Goodtime (yet).

**Comment by rvyhvn** [comment]
any updates?
