### ISSUE TITLE
Vibration continues when work session is started from notification button

### ISSUE THREAD

**Issue by eush77** [adrcotfas/Goodtime#254]
Scenario: the app was In background when break time ended, I clicked "start work" button in the notification. New session started, however, vibration continued through the session.

Expected behavior: the vibration stops with the start of a new session.

App version: 2.2.8.

**Comment by adrcotfas** [comment]
I cannot reproduce this. Is this reproducible every time for you?

**Comment by adrcotfas** [comment]
Please reopen this if it's reproducible for you.
