### ISSUE TITLE
[Feature Request] A setting to change when the day ends (i.e end day at 2AM, etc)

### ISSUE THREAD

**Issue by jaredpereira** [adrcotfas/Goodtime#259]
Hi! Absolutely love the app. 

One small annoyance is that I tend to work late at night, and so the daily statistics don't match up with my experience of work sessions. It'd be great if I could change a setting to roll over the day at 2AM or whatever time I specify.

**Comment by adrcotfas** [comment]
Hi and thanks for the feedback!
I'll keep this in mind for the next version.

**Comment by adrcotfas** [comment]
This was added in version 2.5.0
