### ISSUE TITLE
Current version not available in F-Droid

### ISSUE THREAD

**Issue by Krawei** [adrcotfas/Goodtime#264]
Dear team,
when I take a look on google play store the current version is 2.2.8, in the F-Droid store the current version is 2.2.7.
What's the reason for this gap? Is there a bug in the build process?
Please fix this.
And thanks for your great work!

**Comment by adrcotfas** [comment]
It's weird that F-Droid should update according to the releases. I'll figure it out in the next release (soon).

**Comment by sprlptr48** [comment]
This is still not fixed, are you planning to fix it?

**Comment by adrcotfas** [comment]
I opened an issue here: https://gitlab.com/fdroid/fdroiddata/-/issues/2535

**Comment by sprlptr48** [comment]
I think they answered the question. And thank you for all your effort, creating this awesome app, supporting foss software.

**Comment by adrcotfas** [comment]
I'm glad you like it! I found the root cause and will find a solution soon.
