### ISSUE TITLE
Productivity reminders not working

### ISSUE THREAD

**Issue by 13hannes11** [adrcotfas/Goodtime#293]
The productivity reminder to start using the app is not working for me even though I have scheduled reminders.

**Comment by adrcotfas** [comment]
@13hannes11 What device and OS version are you using?  
Did you shut down/ restart your phone before this occurred?

**Comment by 13hannes11** [comment]
> @13hannes11 What device and OS version are you using?  
> Did you shut down/ restart your phone before this occurred?

Interestingly yesterday I got a reminder for the first time. I will observe the behaviour in the next week and report back.

**Comment by 13hannes11** [comment]
@adrcotfas I am running on the Fairphone 4, Android 11 (build: FP4.FP4I.A.175.20221207) 
After it working once, I continue to not get any reminders.

These are the settings I have:

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/9381167/211523152-11920d12-0abb-4822-86c7-84b03377bb32.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/9381167/211523178-669c6e5b-a393-4c84-a53c-5980507ee18b.png)
