### ISSUE TITLE
[Question] How does productive time work?

### ISSUE THREAD

**Issue by Karmac** [adrcotfas/Goodtime#309]
Hi,

I'm sorry to open an issue just to ask a question, but I could not find the answer anywhere nor figure it out from the code.

What does productive time mean? How is it calculated?

Great app! Thanks.

**Comment by adrcotfas** [comment]
Hi,
It's a distribution graph. The productive time is calculated according to time(hour of day and day of week) and duration of the finished sessions.

A graph with more spikes would mean sessions finished only on certain days whereas a more smooth graph would mean a more consistent work schedule.
