### ISSUE TITLE
Feature Request: Manual Stopwatch Mode

### ISSUE THREAD

**Issue by TheDenast** [adrcotfas/Goodtime#334]
Hi, first of all, absolutely wonderful app! I enjoy using it a lot.

Now, to the request. While pomodoro-style approach is nice, sometimes I want to have flexible work/break lengths. I.e. when starting work session, its counts up as a stopwatch, not down as a timer, then if you swipe the clock, it logs the sessions and continues to act the same way for break.

Sometimes you finish work session, timer rings,  but you feel the need to work additional 5 minutes, not initiate a break. You can always skip the break and initiate next session straight away, but then you feel a little guilty ending that session only several minutes in.

**Comment by tippfehlr** [comment]
You can always swipe up to add a few minutes

**Comment by adrcotfas** [comment]
A count-up option will come in the next major update.
