### ISSUE TITLE
Implement dialogs as notifications

### ISSUE THREAD

**Issue by fdw** [adrcotfas/Goodtime#36]
When the timer is up, the user is asked via a dialog if she wants to continue or stop. Is there a reason why it is implemented as a dialog and not as a regular notification?

If it were done with a notificiation, we could easily implement vibration, sound and LEDs (#16) with it (`setVibrate`, `setSound` and `setLights`, respectively), instead of doing it separately by hand. Besides, it makes more sense from the user's point of view if this is an actionable notification that can pop up instead of making the whole `MainActivity` appear with the dialog on top.

**Comment by adrcotfas** [comment]
There is no reason. At the time of it's implementation, this was the solution that made more sense for me: having a dialog above the app's UI to decide the next actions.
I think it's a good idea to replace the dialog with notifications, but the app UI(at countdown finished) needs to be adapted too.
If the user ignores the notification and just opens the app at countdown finished, I would guess he would like to see "continue"/"skip"/"stop".  Do you have any ideas regarding this?

**Comment by fdw** [comment]
You're right, the activity needs to deal with this as well. I actually do like the dialog for this, but how about we don't bring the application to the front for this? However, when the notification is already up, it should vanish when the user opens the app.

I think this is related to my suggestion in #22, as the app UI and the notification have to be synced - when the user starts a break using the notification, the UI must reflect this as well. A separate TimerService might be a good idea.

**Comment by fdw** [comment]
I think we can close this, too
