### ISSUE TITLE
update Google Play Store page

### ISSUE THREAD

**Issue by adrcotfas** [adrcotfas/Goodtime#47]
- add new screenshots and video according to the recent version
- add localized screenshots for the translated versions

**Comment by Lokesh-Krishna** [comment]
Could it be possible to also add a link to the GitHub repository to make it easy to find?

**Comment by adrcotfas** [comment]
@Lokesh-Krishna Try to click on "Visit website". It's already there.

**Comment by Lokesh-Krishna** [comment]
It indeed is. Sorry about that. 
I only checked the description.

**Comment by adrcotfas** [comment]
Translation project was created: https://poeditor.com/projects/view?id=75697
The store page will be updated with the 1.2.0 release
