### ISSUE TITLE
bug: time label orientation is incorrect on some devices

### ISSUE THREAD

**Issue by JochiPochi** [adrcotfas/Goodtime#50]
Saw this issue on a [Project Tango tablet](https://developers.google.com/tango/hardware/tablet). I'll see if I can replicate on other devices. Might be useful to allow choosing a preferred orientation from the settings menu.

**Comment by adrcotfas** [comment]
@JochiPochi Is the orientation reversed or is the tablet missing the gyro completely?

**Comment by JochiPochi** [comment]
The orientation of the time label is 90 degrees off clockwise no matter what the orientation of the tablet. This [device ](https://developers.google.com/tango/hardware/tablet) has an accelerometer and gyro. The coordinate system on this device is a [bit funky though](https://developers.google.com/tango/overview/coordinate-systems). I could see this happening more often in tablets, where the x axis could be the long or short dimention depending on what the manufacturer decides is the prefered way to hold the device.

**Comment by adrcotfas** [comment]
Fixed with #57
