### ISSUE TITLE
On first run the product tour doesn't take up the full screen

### ISSUE THREAD

**Issue by spagy** [adrcotfas/Goodtime#70]
Observed behaviour: 
![photo](https://cloud.githubusercontent.com/assets/5479401/25290829/1eb8c8a0-26bf-11e7-8e83-e11d5cbe13a4.jpg)

The first time the app is first run it shows the product tour. The app is fullscreen. The notification bar isn't visible but the product tour doesn't take up the space where the notification bar would be. Instead, the top of the timer activity is visible.

Once the product tour has been dismissed the app leaves fullscreen and the timer activity shrinks to its normal size.

Desired behaviour:
Either the app shouldn't enter fullscreen mode in the first place or the app should enter fullscreen mode and the activity tour should take up all of the available space.

I can achieve the first behaviour by removing [the line in the product tour activity that sets the app to full screen](https://github.com/adrcotfas/Goodtime/blob/master/app/src/main/java/com/apps/adrcotfas/goodtime/about/ProductTourActivity.java#L14).

I'm not sure how to make the product tour work in fullscreen. If the first behaviour is acceptable then I'll submit a pull request. Otherwise I'd be happy to have a bit of a dig but I'm not really sure what I'm doing.

**Comment by adrcotfas** [comment]
Interesting, this is not reproducible on my devices.
Sure, please do a PR.
