### ISSUE TITLE
Add 'Disable Mobile Data' to settings

### ISSUE THREAD

**Issue by spagy** [adrcotfas/Goodtime#71]
At the moment there's a 'Disable Wi-Fi' option in the settings. I assume this is so that the phone doesn't receive internet notifications during work sessions. If this is the case then it would make sense to add an option to disable mobile data. Otherwise, it seems likely that, in a lot of cases, disabling wifi will just enable mobile data instead.

**Comment by adrcotfas** [comment]
Unfortunately(the last time I checked) toggling the mobile data is technically impossible with un-rooted devices running Android L or later.
