### ISSUE TITLE
implement a navigation drawer

### ISSUE THREAD

**Issue by adrcotfas** [adrcotfas/Goodtime#8]

**Comment by rdadkins** [comment]
Would it be wise to include a navigation drawer? As it stands, it seems the app has one purpose and that can be changed via settings. What key things could a user navigate to if this route was taken?

**Comment by adrcotfas** [comment]
The app will transform in the future. When new features will be implemented, for example statistics, categories, back-up and sync with Drive, a navigation drawer would be welcome to not change the current main UI too much.

**Comment by adrcotfas** [comment]
Fixed with #57
