### ISSUE TITLE
"functional" Tests with roboelectric

### ISSUE THREAD

**Issue by mataiaslev** [adrcotfas/Goodtime#90]
what do you think about add tests with roboelectric?. If you like it the idea, I can create the structure for this and start to add tests progressively.

my idea, is to change the approach  of the ticket #58. Creating unit tests without restructuring the app. And for that we need to create unit tests "more functional". Because test each part of the app in isolation is so difficult.
I think that create the tests and the refactor at the same tame is dangerous, and probably generate bugs like regressions.

I don't know exactly how much advanced you are with the tests. But I feel like help in that.

Thanks!

**Comment by adrcotfas** [comment]
> I don't know exactly how much advanced you are with the tests. But I feel like help in that.

There are no tests implemented for the app.

To be honest, I would prefer to have the app refactored in a MVP fashion and implement tests along the way.
Thank you for your intention to implement a functional test and if you want to, please go ahead!
But beware, it's very possible that in the near future I will refactor the whole app and implement unit tests for all the layers in isolation and your tests may become obsolete.

**Comment by mataiaslev** [comment]
I understand, i have experience creating a project in android using MVP, dagger, roboelectric from the beginning.  And on the other hand I have experience refactoring a nodejs api without tests. The approach with the api is start with functional tests. And then move to the refactor. in android we need to wait a long time for run funcitonal tests. for that, The best approach that i can imagine is create unit tests without isolation. Then move to the refactor. 

anyway, I want to help with this if you let me. We can have a talk about it from hangouts or something if you feel interest.

I prefer to go ahead with something than help you!

**Comment by adrcotfas** [comment]
The code as it is right now is very hard to unit-test. How can you create unit tests without isolation? It would need a lot of mocks.

**Comment by mataiaslev** [comment]
like mini-integration tests, maybe I can't. I will try, and tell you what happend.

thanks for your answers!

**Comment by mataiaslev** [comment]
I spent some time with the code and I did some tries but at the end is like you say. If i can help in something with the refactor to MVP and the tests just tell me.

I will close the issue. Thanks!
